version : '3.7'

services:

  mysql:
    image: mysql:latest
    container_name: dev_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-root}
    volumes:
      - "data:/var/lib/mysql"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_PASSWORD:-root}
    ports:
      - 8183:80
    restart: always

volumes:
  data: